version: "3.9"
services:
  mysql-db:
    image: mysql:8.0
    restart: unless-stopped
    container_name: 'mysql-db'
    environment:
      MYSQL_DATABASE: "mysql"
      MYSQL_ALLOW_EMPTY_PASSWORD: true
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql

  phpmyadmin:
    image: bitnami/phpmyadmin:latest
    restart: unless-stopped
    ports:
      - 8182:8182
    environment:
      - DATABASE_HOST=mysql-db
      - DATABASE_PORT_NUMBER=3306
      - PMA_ARBITRARY=1
      - APACHE_HTTP_PORT_NUMBER=8182
      - DATABASE_USER=root
      - DATABASE_PASSWORD=

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    expose:
      - 8081
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      
  postgresql-db:
    image: "postgres:latest"
    container_name: postgresql-db
    environment:
      POSTGRES_USER: hoanle396 
      POSTGRES_PASSWORD: hoanle396 
      POSTGRES_DB: iconnect 
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-4
    environment:
      PGADMIN_DEFAULT_EMAIL: hoanle396@gmail.com
      PGADMIN_DEFAULT_PASSWORD: hoanle396
    ports:
      - 81:80
    volumes:
      - /var/lib/pgadmin
    links:
      - "postgresql-db:pgsql-server"  
    restart: unless-stopped
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
        - redis-data:/var/lib/redis/data
    networks:
        - app-network #same network here
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
        - REDIS_HOSTS=local:redis:6379
        - PORT=8001
    expose:
        - 8001
    ports:
        - "8001:8001"
    depends_on:
        - redis
    networks:
        - app-network
volumes:
  mysql-db:
  mongo:
  db-data:
  redis-data:
networks:
  app-network:
    driver: bridge
  kafka-network:
    driver: bridge
    name: kafka-network
  notifications-network:
    external: true